dist: xenial
os: linux
git:
  depth: 3 

jobs:
  include:
    # ======== Parte del frontend ========
    - language: node_js
      node_js:  '12'

      warnings_are_errors: false

      cache: 
        directories:
          - node_modules

      branches:
        only:
          - master

      before_install: 
        - cd Frontend/

      install:
        - npm install
      script:
        - npm run build

      deploy:
        provider: firebase
        skip_cleanup: true
        token: $FIRE_TOKEN
    
    # ======== Parte de Backend ========
    - language: python
      python:
        - "3.6"

      cache: pip

      branches:
        only:
          - master

      env:
        - DJANGO=3.0

      before_install:
        - cd Backend/

      install:
        - "pip install -r requirements.txt"

      script: 
        - python src/manage.py test

      deploy:
        provider: heroku
        api_key: ceb5ac04-5ab8-4ccf-b813-f22b4865abfb
        app: energycorp
        on: 
          repo: esneidermanzano/energyCorp
          branch: master